// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGn9RJl9UrMHtgTlSK6iNuwExjn6C2TUg',
    appId: '1:208270752370:web:2e6083dc86d8263765a0eb',
    messagingSenderId: '208270752370',
    projectId: 'exampleproject-2d74c',
    authDomain: 'exampleproject-2d74c.firebaseapp.com',
    databaseURL: 'https://exampleproject-2d74c-default-rtdb.firebaseio.com',
    storageBucket: 'exampleproject-2d74c.firebasestorage.app',
    measurementId: 'G-QCZ1NEZ861',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUhXAmZ5yUYIkbJHk-8ow7rbvcN6-_BeA',
    appId: '1:208270752370:android:78f57c71b001b6db65a0eb',
    messagingSenderId: '208270752370',
    projectId: 'exampleproject-2d74c',
    databaseURL: 'https://exampleproject-2d74c-default-rtdb.firebaseio.com',
    storageBucket: 'exampleproject-2d74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDipgPD9-sbSLdiZcCpvdzJeH_94Vve7nw',
    appId: '1:208270752370:ios:cc163c4e9338235565a0eb',
    messagingSenderId: '208270752370',
    projectId: 'exampleproject-2d74c',
    databaseURL: 'https://exampleproject-2d74c-default-rtdb.firebaseio.com',
    storageBucket: 'exampleproject-2d74c.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDipgPD9-sbSLdiZcCpvdzJeH_94Vve7nw',
    appId: '1:208270752370:ios:cc163c4e9338235565a0eb',
    messagingSenderId: '208270752370',
    projectId: 'exampleproject-2d74c',
    databaseURL: 'https://exampleproject-2d74c-default-rtdb.firebaseio.com',
    storageBucket: 'exampleproject-2d74c.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGn9RJl9UrMHtgTlSK6iNuwExjn6C2TUg',
    appId: '1:208270752370:web:ce16055448067a8b65a0eb',
    messagingSenderId: '208270752370',
    projectId: 'exampleproject-2d74c',
    authDomain: 'exampleproject-2d74c.firebaseapp.com',
    databaseURL: 'https://exampleproject-2d74c-default-rtdb.firebaseio.com',
    storageBucket: 'exampleproject-2d74c.firebasestorage.app',
    measurementId: 'G-FRPWKWDTR7',
  );
}
